language: c
compiler: gcc
sudo: true

notifications:
  email: false
  irc: "chat.freenode.net#keeto"

before_install:
  - sudo add-apt-repository "deb http://de.archive.ubuntu.com/ubuntu trusty main
        restricted universe multiverse"
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y autotools-dev autoconf automake check libconfuse-dev
    libpam0g-dev libssl-dev libtool

before_script:
  - ./autogen.sh

script:
  - ./configure
  - make
  - make check
  - cat test/test-suite.log

