language: c
compiler: gcc
sudo: false

notifications:
  email: false
  irc: "chat.freenode.net#pam-openssh-x509"

addons:
  apt:
    sources:
      - sourceline: 'deb http://de.archive.ubuntu.com/ubuntu trusty main
        restricted universe multiverse'
    packages:
      - autotools-dev
      - autoconf
      - automake
      - check
      - doxygen
      - libconfuse-dev
      - libpam0g-dev
      - libssl-dev
      - libtool

#before_install:
#    - sudo add-apt-repository "deb http://de.archive.ubuntu.com/ubuntu trusty
#        main restricted universe multiverse"
#    - sudo apt-get update -qq

#install:
#    - sudo apt-get install -y autotools-dev autoconf automake check doxygen
#        libconfuse-dev libpam0g-dev libssl-dev libtool

before_script:
  - ./autogen.sh
#  - sudo mkdir -p /usr/local/etc/ssh/cacerts

script:
  - ./configure --libdir=/lib/security --disable-dependency-tracking
  - make
#  - make check

